server:
  port: 8080
database:
  url: jdbc:postgresql://localhost:5432/postgres
  driver_class: org.postgresql.ds.PGSimpleDataSource
  user: user
  password: pass
  uri: postgresql://user:pass@localhost:5432/postgres
